### PR TITLE
added reverse script

### LINKED ISSUE #8: Developing reverse-a-string.js
TO DO:
- [x] Develop function ``` reverseString()```
- [x] Test its behaviour
- [x] Add to the interface

### PR DESCRIPTION
**Pull request by LujiAnna**
Relates #8

### CODE REVIEW

**Review by fmkarakus — COMMENTED** [review]
Nicely done!

**Review by pavelbidenko2018 — APPROVED** [review]
All seems to work fine!

**Review by gelilaa — APPROVED** [review]
Looks Very good!

**Comment by LujiAnna** [comment]
Thanks guys!
should I merge it then?

**Pull request merged**
